"""add grid trading models

Revision ID: 20240604_add_grid
Revises: 20240503_add_chatroom_fields
Create Date: 2024-06-04 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20240604_add_grid'
down_revision = '20240503_add_chatroom_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_strategies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('exchange', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('grid_type', sa.String(), nullable=False),
        sa.Column('strategy_type', sa.String(), nullable=False, server_default='NEUTRAL'),
        sa.Column('market_type', sa.String(), nullable=False, server_default='FUTURES'),
        sa.Column('upper_price', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('lower_price', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('grid_number', sa.Integer(), nullable=False),
        sa.Column('total_investment', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('per_grid_amount', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column('leverage', sa.Integer(), nullable=True),
        sa.Column('stop_loss', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column('take_profit', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column('profit_collection', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('status', sa.String(), nullable=False, server_default='CREATED'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('symbol_price_precision', sa.Integer(), nullable=True),
        sa.Column('symbol_qty_precision', sa.Integer(), nullable=True),
        sa.Column('symbol_min_qty', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column('symbol_min_notional', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column('symbol_max_leverage', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_strategies_id'), 'grid_strategies', ['id'], unique=False)
    
    op.create_table('symbol_rules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('exchange', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('price_precision', sa.Integer(), nullable=False),
        sa.Column('quantity_precision', sa.Integer(), nullable=False),
        sa.Column('min_quantity', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('min_notional', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('max_leverage', sa.Integer(), nullable=True),
        sa.Column('taker_fee', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('maker_fee', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('contract_value', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('exchange', 'symbol', name='uix_exchange_symbol')
    )
    op.create_index(op.f('ix_symbol_rules_id'), 'symbol_rules', ['id'], unique=False)
    
    op.create_table('grid_orders',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('strategy_id', sa.Integer(), nullable=True),
        sa.Column('exchange', sa.String(), nullable=False),
        sa.Column('symbol', sa.String(), nullable=False),
        sa.Column('grid_index', sa.Integer(), nullable=False),
        sa.Column('price', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column('side', sa.String(), nullable=False),
        sa.Column('order_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('filled_at', sa.DateTime(), nullable=True),
        sa.Column('profit', sa.Numeric(precision=28, scale=8), nullable=True),
        sa.ForeignKeyConstraint(['strategy_id'], ['grid_strategies.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grid_orders_id'), 'grid_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grid_orders_id'), table_name='grid_orders')
    op.drop_table('grid_orders')
    op.drop_index(op.f('ix_symbol_rules_id'), table_name='symbol_rules')
    op.drop_table('symbol_rules')
    op.drop_index(op.f('ix_grid_strategies_id'), table_name='grid_strategies')
    op.drop_table('grid_strategies')
    # ### end Alembic commands ### 